### ISSUE TITLE
[FE] 상세 애니메이션 다 넣기

### ISSUE THREAD

**Issue by jijiseong** [softeerbootcamp-2nd/A2-CarTag#104]
## Description

상세 애니메이션 다 넣기

## Todo

- [x] 트림 페이지
- [x] 페이지 전환 애니메이션 수정
- [ ] 모델 타입 페이지
- [ ] 외장 색상 선택 페이지
- [ ] 내장 색상 선택 페이지
- [ ] 옵션 선택 페이지
- [x] 결과 페이지
