### ISSUE TITLE
[BE] CI/CD 환경 구축

### ISSUE THREAD

**Issue by tank3a** [softeerbootcamp-2nd/A2-CarTag#118]
## Description
dev -> main으로 PR 날라올 때 CI 환경을 구축하고, EC2와 S3에 배포

## Todo
- [x] Gradle 자동화 빌드환경을 구축
- [x] Npm 자동화 빌드환경을 구축
- [x] EC2에 서버 배포
- [x] S3에 서버 배포

**Comment by tank3a** [comment]
@dydwo0740 용재님 고생하셨습니다!
