### ISSUE TITLE
[BE] 견적 더미데이터 자동생성 프로그램 생성

### ISSUE THREAD

**Issue by tank3a** [softeerbootcamp-2nd/A2-CarTag#119]
## Description
Python을 이용한 판매견적 데이터 자동 생성 프로그램을 생성한다.

## Todo
- [ ] 자동 프로그램 생성
- [ ] 데이터 csv파일로 저장
- [ ] AWS EC2 DB에 데이터 저장

## etc
다른 너티야 조와 협업하여 데이터 통일 예정
