### ISSUE TITLE
[BE] 유사 견적 데이터 제공 기능

### ISSUE THREAD

**Issue by tank3a** [softeerbootcamp-2nd/A2-CarTag#12]
## Description
유사견적 조회 버튼 클릭 시 유사 견적의 데이터 전체를 제공, 유사 견적에 있는 옵션 중 현재 견적에 존재하지 않는 옵션(최대 2개)를 제공

## Todo
- [ ] 유사견적 ID를 가지고 금액 차이 반환
- [ ] 해당 유사견적 리스트의 데이터 반환
- [ ] 현재 견적과 옵션 차이 반환
