### ISSUE TITLE
[BE] 견적 공유 기능

### ISSUE THREAD

**Issue by tank3a** [softeerbootcamp-2nd/A2-CarTag#13]
## Description
견적서가 완료된 후, 견적서를 공유할 때 PDF, 소셜로 공유할 수 있도록 한다.

## Todo
- [ ] 견적서 데이터 받아오는 부분
- [x] PDF로 추출하는 부분
- [ ] 소셜(카카오, 네이버 등)으로 추출
- [ ] 클라이언트에게 견적 완료 여부 전송
