### ISSUE TITLE
[FE] 2주차 중간 리팩토링

### ISSUE THREAD

**Issue by jijiseong** [softeerbootcamp-2nd/A2-CarTag#138]
## Description

2주차 중간 리팩토링

## Todo

- [x] components 폴더 구조 변경 (common 분리)
- [x] containers 내에서 중복 사용 컴포넌트 따로 빼기
- [x] (props) -> ({theme}) 수정
- [x] interface, function 순서 
- [x] export default로 통일
- [ ] 기타 등등.. 보면서 추가
