### ISSUE TITLE
[FE] 온보딩(가이드) 컴포넌트

### ISSUE THREAD

**Issue by kimdaye77** [softeerbootcamp-2nd/A2-CarTag#151]
## Description
처음 시작할 때 온보딩(가이드) 컴포넌트 UI 구현

## Todo
- [x] 배경 딤드 처리
- [x] 가이드 말풍선 UI 구현
- [x] 딤드 선택하면 말풍선 닫기
