### ISSUE TITLE
[BE] suboption과 defaultoption을 통합합니다.

### ISSUE THREAD

**Issue by dydwo0740** [softeerbootcamp-2nd/A2-CarTag#174]
## Description

option관련 클래스들을 수정합니다.

## Todo

- [x] suboption 과 defauloption 영역을 통합합니다.
- [x] defaultoption 관련 repository를 기존에 이용하던 service를 수정합니다.
- [x] suboption 관련 dto 이름 수정합니다.
- [x] defaultoption 관련 dto 이름 수정합니다.
