### ISSUE TITLE
[FE] UI 버그 수정

### ISSUE THREAD

**Issue by kimdaye77** [softeerbootcamp-2nd/A2-CarTag#178]
## Description

UI 버그 수정

## Todo
- [x] 견적 완료 페이지 detail 클릭 이벤트 범위 수정
- [x] 가이드 모달 홈 화면 외에는 렌더링 금지
- [x] trim page Hmg data zindex 수정 (종료 모달 노출시 ui  버그)
- [x] 결과 페이지 마진 수정
