### ISSUE TITLE
[BE] DB 성능 최적화 및 리팩토링

### ISSUE THREAD

**Issue by tank3a** [softeerbootcamp-2nd/A2-CarTag#225]
## Description
DB 성능 최적화를 위해 쿼리문 개선, 코드 리팩토링을 진행한다.

## Todo
- [ ] Redis를 이용하여 유사견적 데이터 호출 속도 개선
- [ ] 쿼리문 개선으로 연산속도 개선
- [ ] 코드 리팩토링
- [ ] 테스트 코드 개선

## etc
개선 시 속도차이 스크린샷 필수!
