### ISSUE TITLE
[FE] UI 버그 수정

### ISSUE THREAD

**Issue by jijiseong** [softeerbootcamp-2nd/A2-CarTag#328]
## Todo

- [x] RectButton hover 수정
- [x] 결과 페이지 이미지 url 수정
- [x] 옵션 페이지 이미지 비율 수정
- [x] 내장 색상 페이지 배너 깜빡임 수정
