### ISSUE TITLE
[FE] UI 버그 수정

### ISSUE THREAD

**Issue by jijiseong** [softeerbootcamp-2nd/A2-CarTag#392]
## Description

자잘한 UI 버그 수정

## Todo

- [x] 모델 타입 효율 영역
- [x] 모델 타입 블루 텍스트
- [x] 예산 설정 바 설정 가격 표시
- [x] 예산 설정 바 step 10만원 수정
- [x] 로컬 이미지 지우기
- [x] navbar 자동차 종류 표시
- [ ] 옵션 길때 수정
