### ISSUE TITLE
[BE] 백엔드 리팩토링(Car 관련)

### ISSUE THREAD

**Issue by tank3a** [softeerbootcamp-2nd/A2-CarTag#407]
## Description
Car와 관련된 부분들의 구현코드와 테스트 리팩토링 진행

## Todo
- [ ] 성능 향상
- [ ] 코드 가독성 높이기
- [ ] Swagger API 가독성 개선
- [ ] DTO & BUILDER 고찰
