### ISSUE TITLE
[BE] 유사 견적 요약정보(막대그래프) 제공

### ISSUE THREAD

**Issue by tank3a** [softeerbootcamp-2nd/A2-CarTag#41]
## Description
현재 견적의 점수를 가지고, 실제 판매된 견적들과 비교하여 유사견적(threshold 이상) 최대 4개를 호출
- main task: #11 

## Todo
- [x] 실제 견적들의 점수 확인
- [x] 견적 점수와 점수 비교
- [x] 유사견적 ID와 판매량 반환
- [ ] 데이터 존재하지 않을 시 처리
- [ ] 테스트 코드 작성
