### ISSUE TITLE
[BE] Model 도메인 관련 리팩토링

### ISSUE THREAD

**Issue by tank3a** [softeerbootcamp-2nd/A2-CarTag#419]
## Description
Model과 관련한 클래스들을 하나의 패키지로 묶고 리팩토링 진행. 테스트 코드 수정
- main task: #225 

## Todo
- [ ] 하나의 패키지로 묶기
- [ ] 코드 리팩토링 진행
- [ ] 쿼리 성능 개선점 찾기
- [ ] 테스트 코드 수정
