### ISSUE TITLE
[FE] 버그 리포트 - sub03 (전체적인 품질 향상)

### ISSUE THREAD

**Issue by kimdaye77** [softeerbootcamp-2nd/A2-CarTag#435]
### TODO
[값 바꿀 것]
- [x] DEBOUNCE TIME  300
- [x] 최고금액 5677만원

[유사견적 UI]
- [x] 로딩 중간으로
- [x] 바 텍스트 유사 견적으로 변경
- [x] 예산 설정바 최저최고 금액 정보 2개있음

[결과페이지]
- [x] 외장 내장 순서
- [x] 이미지 비율

[기타]
- [x] 옵션 fixed
- [x] 견적 요약 UI
- [ ] 페이지 이동 시 스크롤 맨위로
